# Outline
- PyTorch
- What are tensors
- Initializing, slicing , reshaping tensors
- Numpy and PyTorch interfacing
- GPU support for PyTorch + Enabling GPU on Colab
- Speed comparisons, Numpy vs PyTorch on GPU
- Autograds concepts and application
- Writing a basic learning loop using autograd
- Exercises

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Initialise tensors

In [2]:
x = torch.ones(3,2)
print(x)

y = torch.rand(3,2)
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.5226, 0.6428],
        [0.1544, 0.0704],
        [0.2021, 0.0070]])


In [3]:
x = torch.empty(5,3)
print(x)

y = torch.zeros_like(x)
print(y)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  7.5823e+18,  3.2357e-41],
        [ 8.1211e+17,  3.2357e-41, -3.3318e+26],
        [ 4.3345e-41,  1.4013e-45,  0.0000e+00],
        [ 8.4078e-45,  0.0000e+00,  0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.linspace(0,1,5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [5]:
y = torch.tensor([[1,2],
 [3,4],
 [5,6]])
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


# Slicing tensors

In [6]:
print(y.size())
print(y[:,1])
print(y[1,:])
print(y.view(2,3))

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([3, 4])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
y = x[1]
print(y)
print(y.item())

tensor(0.2500)
0.25


# Reshaping tensors

In [8]:
print (x)
z = x.view(-1)
print(z)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


# Simple Tensor Operations

In [9]:
x = torch.ones(2,2, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
z = y.add_(5)
print(z, out)
print(y)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<AddBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[8., 8.],
        [8., 8.]], grad_fn=<AddBackward0>)


In [11]:
z = y.add(x)
print(z, out)
print(y)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<AddBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[8., 8.],
        [8., 8.]], grad_fn=<AddBackward0>)


# Numpy <> PyTorch

In [12]:

# Creating NumPy arrays
a_np = np.array([[1, 2], [3, 4]])
b_np = np.array([[5, 6], [7, 8]])

# Converting NumPy arrays to PyTorch tensors
a = torch.tensor(a_np)
b = torch.tensor(b_np)

# Checking shapes
if a.shape[1] != b.shape[0]:
    raise ValueError("Shapes mismatch for matrix multiplication")

# Performing matrix multiplication
c = torch.matmul(a, b)

# Converting result to NumPy array for display
c_np = c.numpy()

print("Matrix A:")
print(a)
print("\nMatrix B:")
print(b)
print("\nResult:")
print(c_np)


Matrix A:
tensor([[1, 2],
        [3, 4]])

Matrix B:
tensor([[5, 6],
        [7, 8]])

Result:
[[19 22]
 [43 50]]


In [13]:
import torch
import numpy as np
import time

# Create large NumPy arrays and PyTorch tensors
numpy_array = np.random.rand(1000, 1000)
torch_tensor = torch.rand(1000, 1000)

# NumPy operation
start_time = time.time()
result_numpy = np.sqrt(numpy_array)
numpy_time = time.time() - start_time

# PyTorch operation
start_time = time.time()
result_torch = torch.sqrt(torch_tensor)
torch_time = time.time() - start_time

print("NumPy time:", numpy_time)
print("PyTorch time:", torch_time)


NumPy time: 0.003112316131591797
PyTorch time: 0.017456769943237305


In [14]:
%%time
for i  in range (10):
  a = np.random.randn(10000, 10000)
  b = np.random.randn(10000, 10000)
  c = a+b

CPU times: user 55.8 s, sys: 4.32 s, total: 1min
Wall time: 1min 2s


In [15]:
%%time
for i  in range (10):
  a = torch.randn([10000, 10000])
  b = torch.randn([10000, 10000])
  c = a+b

CPU times: user 14.1 s, sys: 6.65 s, total: 20.8 s
Wall time: 19.9 s


#CUDA support for PyTorch

In [16]:
print(torch.cuda.is_available())

True


In [17]:
print(torch.cuda.device_count())

1


In [19]:
print(torch.cuda.get_device_name(0))


Tesla T4


In [20]:
cuda0 = torch.device('cuda:0')

In [21]:
a = torch.ones(2,2, device=cuda0)
print(a)
b = torch.ones(2,2, device=cuda0)
print(b)
c = a + b
print(c)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.]], device='cuda:0')


In [22]:
%%time
for i  in range (10):
  a = np.random.randn(10000, 10000)
  b = np.random.randn(10000, 10000)
  np.add(b,a)

CPU times: user 54.9 s, sys: 4.38 s, total: 59.2 s
Wall time: 59.3 s


In [23]:
%%time
for i  in range (10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  c = a+b

CPU times: user 1.84 ms, sys: 3.98 ms, total: 5.82 ms
Wall time: 16 ms


In [24]:
%%time
for i  in range (10):
  a = np.random.randn(10000, 10000)
  b = np.random.randn(10000, 10000)
  np.matmul(b,a)

CPU times: user 16min 31s, sys: 16.3 s, total: 16min 47s
Wall time: 10min 8s


In [25]:
%%time
for i  in range (10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  c = torch.matmul(a,b)

CPU times: user 32.1 ms, sys: 14.9 ms, total: 47.1 ms
Wall time: 138 ms


# Autograd

In [27]:
x = torch.ones(5, requires_grad=True)
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [28]:
x = torch.ones([3,2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [29]:
y = x + 5
print(y)
print(y.grad_fn)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [31]:
z = y * y +1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [32]:
t =torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [33]:
t.backward()

In [34]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


#
$$ t = \sum_{i} z_i,z_i = \sum_{i} y_i^2 + 1, y_i = x_i + 5
$$
$$\frac{\partial t}{\partial x_i} = \frac{\partial z_i}{\partial x_i} = \frac{\partial y_i}{\partial x_i} = 2y_i *1
$$
$$ At , x=1,  y=6,  \frac{\partial t}{\partial x_i} = 12$$



In [35]:
x = torch.ones([3,2], requires_grad=True)
y = x + 5
r = 1/(1+torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)


tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [36]:
x = torch.ones([3,2], requires_grad=True)
y = x + 5
r = 1/(1+torch.exp(-y))
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


$$ \frac {\partial s}{\partial x} = \frac{\partial s}{\partial r} . \frac{\partial r}{\partial x} $$

For the above code a represents $$ \frac {\partial s}{\partial r} $$ and then x.grad gives directly $$ \frac{\partial s}{\partial x} $$

# Autograd examples that looks like what we have been doing so far

In [ ]:
x = torch.randn([20, 1], requires_grad=True)
y = 3 * x - 2
print(x)
print(y)

In [38]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

y_hat = w * x + b
loss = torch.sum(torch.pow(y_hat - y, 2.0))

print(loss)
loss.backward()
print(w.grad)
print(b.grad)

tensor(300.0010, grad_fn=<SumBackward0>)
tensor([-95.3930])
tensor([136.4053])


# Do it in loop

In [40]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print(w.item(), b.item())

for i in range(10):
  x = torch.randn([20, 1])
  y = 3 * x - 2

  y_hat = w * x + b
  loss = torch.sum(torch.pow(y_hat - y, 2.0))

  loss.backward()

  with torch.no_grad():
      w -= learning_rate * w.grad
      b -= learning_rate * b.grad

      # Manually zero the gradients after running the backward pass
      w.grad.zero_()
      b.grad.zero_()
  print(w.item(), b.item())

1.0 1.0
2.3520750999450684 -0.3464607000350952
2.683164119720459 -1.0461140871047974
2.67490291595459 -1.381699562072754
2.7550041675567627 -1.6306308507919312
2.835728645324707 -1.7580153942108154
2.8592982292175293 -1.8461899757385254
2.963571071624756 -1.9269379377365112
2.990159511566162 -1.9600303173065186
2.996389150619507 -1.9766826629638672
2.9960744380950928 -1.9857265949249268


# Do it for a large problem

In [ ]:
%%time
learning_rate = 0.0001  # Reduced learning rate
N = 100
epochs = 2000

w = torch.tensor(1., requires_grad=True)
b = torch.tensor(1., requires_grad=True)

print(w.item(), b.item())

for i in range(epochs):
  x = torch.randn(N)
  y = torch.sum(3 * torch.ones(N) * x) - 2

  y_hat = torch.sum(w * x) + b
  loss = torch.sum((y_hat - y) ** 2.0)

  loss.backward()

  with torch.no_grad():
      w -= learning_rate * w.grad
      b -= learning_rate * b.grad

      # Manually zero the gradients after updating
      w.grad.zero_()
      b.grad.zero_()
  print(w.item(), b.item())


In [ ]:
%%time
learning_rate = 0.0000001  # Reduced learning rate
N = 1000000
epochs = 2000

w = torch.tensor(1., requires_grad=True, device=cuda0)
b = torch.tensor(1., requires_grad=True, device=cuda0)

print(w.item(), b.item())

for i in range(epochs):
  x = torch.randn(N, device=cuda0)
  y = torch.sum(3 * torch.ones([N ], device=cuda0) * x) - 2

  y_hat = torch.sum(w * x) + b
  loss = torch.sum((y_hat - y) ** 2.0)

  loss.backward()

  with torch.no_grad():
      w -= learning_rate * w.grad
      b -= learning_rate * b.grad

      # Manually zero the gradients after updating
      w.grad.zero_()
      b.grad.zero_()
  print(w.item(), b.item())
